# Generated by Django 6.0 on 2025-12-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name_plural": "about"},
        ),
        migrations.RenameField(
            model_name="about",
            old_name="about_body",
            new_name="body",
        ),
        migrations.RenameField(
            model_name="about",
            old_name="about_heading",
            new_name="heading",
        ),
    ]
