# Generated by Django 6.0 on 2025-12-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_alter_about_options_rename_about_body_about_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="body",
            field=models.TextField(max_length=500),
        ),
    ]
