# Generated by Django 6.0 on 2025-12-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_alter_about_body"),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
    ]
